# 本地 Docker Desktop 开发配置
# 简化版本：只包含必要的服务，适合本地快速启动

version: '3.8'

services:
  # 像素画转换器应用（前后端合并）
  pixel-art-local:
    build:
      context: ./backend
      dockerfile: Dockerfile.simple
    container_name: pixel-art-local
    restart: unless-stopped
    
    # 端口映射
    ports:
      - "3001:3001"  # 后端API和前端页面
    
    # 环境变量
    environment:
      - NODE_ENV=production
      - PORT=3001
      # 本地开发：禁用数据库和Redis
      - ENABLE_DATABASE=false
      - ENABLE_REDIS_CACHE=false
      # CORS配置：允许本地访问
      - ALLOWED_ORIGINS=http://localhost:3001,http://127.0.0.1:3001,http://localhost:5173
      # 文件上传配置
      - MAX_FILE_SIZE=10485760
      - ALLOWED_FILE_TYPES=image/jpeg,image/png,image/gif,image/webp
      # 日志级别
      - LOG_LEVEL=info
    
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # 标签
    labels:
      - "app=pixel-art-converter"
      - "environment=local"
      - "managed-by=docker-compose"

# 说明：
# 1. 确保已构建前端（运行 cd frontend && npm run build）
# 2. 启动命令：
#    docker-compose -f docker-compose.local.yml up -d --build
# 3. 访问地址：
#    http://localhost:3001
# 4. 停止命令：
#    docker-compose -f docker-compose.local.yml down
# 5. 查看日志：
#    docker-compose -f docker-compose.local.yml logs -f

